title: Máté Kocsis
description: My professional blog
email: kocsismate@woohoolabs.com





baseurl: ""
url: "/"
permalink: pretty
encoding: "utf-8"

highlighter: rouge
paginate: 10
exclude: ["_import", "Gemfile", "Gemfile.lock"]
markdown: kramdown
kramdown:
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

gems:
  - jemoji
  - jekyll-paginate

logo: "/assets/images/author.jpg"
cover: "/assets/images/background_image.jpg"

author: "Máté Kocsis"
author_image: "/assets/images/author.jpg"
author_bio: ""
disqus: kocsismate

social:
  - icon: twitter
    url: https://twitter.com/kocsismate90
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url: https://github.com/kocsismate
    desc: Fork me on github
    share_url:
    share_title:
    share_link:
