# Build settings
gems:
  - "jemoji"
  - "jekyll-paginate"

# Site settings
title: "Máté Kocsis"
description: >
   Software Developer in Budapest, Hungary @ IBM Cloud Video.<br/>
   Enjoys PHP, Domain-Driven Design, REST, and Continuous Delivery.<br/>
   Father of multiple open source projects.
email: "kocsismate@woohoolabs.com"
logo: "/assets/image/author.jpg"
cover: "/assets/image/background_image.jpg"
float_logo: true
cover: "/assets/image/typewriter.jpg"

url: "https://kocsismate.github.io"
baseurl: ""
paginate:	10
permalink: pretty
encoding: "utf-8"

# Author settings
name: "Máté Kocsis"
author: "Máté Kocsis"
author_image: "/assets/image/author.jpg"

# Social settings
twitter_handle: "@kocsismate90"
disqus: "kocsismate"
google_analytics: UA-90649601-1

social:
  - icon:	"twitter"
    url:	"https://twitter.com/kocsismate90"
    desc: "Follow me on twitter"
    share_url: "http://twitter.com/share"
    share_title: "?text="
    share_link: "&amp;url="

  - icon:	"github"
    url:	"https://github.com/kocsismate"
    desc:	"Fork me on github"
    share_url:
    share_title:
    share_link:
